
export const mealTypes = [
      "Main course",
      "Side dish",
      "Dessert",
      "Appetizer",
      "Salad",
      "Bread",
      "Breakfast",
      "Soup",
      "Beverage",
      "Sauce",
      "Marinade",
      "Finger food",
      "Snack",
      "Drink",
    ]

export const dietOption = [
      "Pescatarian",
      "Gluten free",
      "Lacto ovo vegetarian",
      "Primal",
      "Vegan",
      "Dairy free",
      "Whole 30",
      "Ketogenic",
      "Paleolithic",
      "Fodmap friendly"
    ]

export const cuisineOption = [
      "African",
      "Asian",
      "American",
      "British",
      "Cajun",
      "Caribbean",
      "Chinese",
      "Eastern European",
      "European",
      "French",
      "German",
      "Greek",
      "Indian",
      "Irish",
      "Italian",
      "Japanese",
      "Jewish",
      "Korean",
      "Latin American",
      "Mediterranean",
      "Mexican",
      "Middle Eastern",
      "Nordic",
      "Southern",
      "Spanish",
      "Thai",
      "Vietnamese"
    ]